trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

jobs:
- template: build-bindings-job.yml
  parameters:
    name: Linux
- template: build-bindings-job.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
