src = $(wildcard *.c)
obj = $(src:.c=.o)

.PHONY : clean
.PHONY: test

CPPFLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -Wall --std=c++11 -fPIC $(shell python3 -m pybind11 --includes) -I$CONDA_PREFIX/include/opencascade -g
LDFLAGS= -shared

SOURCES = $(wildcard *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

TARGET={{namne}}.$(shell python3-config --extension-suffix)

all: $(TARGET)

clean:
    rm -f $(OBJECTS) $(TARGET)

$(TARGET) : $(OBJECTS)
    $(CC) $(CFLAGS) $(OBJECTS) -o $@ $(LDFLAGS)
    
test:
    ipython -i -e"import {{name}}"